// src/components/NegotiationCard.jsx

function inr(n) {
  if (n === null || n === undefined) return "—";
  return "₹" + Math.round(n).toLocaleString("en-IN");
}

const VERDICT_LABEL = {
  borrow: "Proceed with this loan",
  borrow_less: "Proceed, but at a lower amount",
  dont_borrow: "Not a good time to borrow",
};

export default function NegotiationCard({ answers, results, onBack }) {
  const { verdict, affordability, rateband, emi } = results;

  function handlePrint() {
    window.print();
  }

  return (
    <div className="min-h-screen bg-bg2 px-4 py-10 print:bg-white print:py-0">
      <div className="max-w-xl mx-auto">
        {/* controls — hidden on print */}
        <div className="flex items-center justify-between mb-5 print:hidden">
          <button
            onClick={onBack}
            className="text-sm text-muted hover:text-ink transition-colors font-body"
          >
            ← Back to results
          </button>
          <button
            onClick={handlePrint}
            className="bg-accent text-accentInk px-5 py-2 text-sm font-semibold tracking-wide font-body hover:opacity-90 transition-opacity"
          >
            Print / Save as PDF
          </button>
        </div>

        {/* the card itself */}
        <div className="bg-bg border border-ink px-8 py-9 print:border-0 print:px-0">
          <div className="flex items-center justify-between border-b border-rule pb-4 mb-6">
            <div>
              <p className="text-[.7rem] font-semibold tracking-[.14em] uppercase text-muted font-body">
                Negotiation Card
              </p>
              <h1 className="font-display font-medium text-[1.5rem] text-ink mt-1">
                What's fair for this loan
              </h1>
            </div>
            <p className="text-[.75rem] text-muted font-mono">
              {new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}
            </p>
          </div>

          {/* verdict strip */}
          <div className="mb-7">
            <p className="text-[.7rem] uppercase tracking-[.08em] text-muted font-body mb-1">Verdict</p>
            <p className="font-display font-medium text-[1.25rem] text-accent">
              {VERDICT_LABEL[verdict.verdict]}
            </p>
          </div>

          {/* the four facts in a tight grid */}
          <div className="grid grid-cols-2 gap-x-6 gap-y-5 mb-7">
            <Fact label="Loan asked" value={inr(answers.amountWanted)} />
            <Fact label="Safe to carry" value={inr(affordability.safeMax)} strong />
            <Fact label="Fair rate range" value={`${rateband.rateMin}% – ${rateband.rateMax}%`} strong />
            <Fact label="All-in APR" value={`${rateband.apr}%`} />
            <Fact label="EMI ceiling" value={`${inr(emi.emiCeiling)}/mo`} strong />
            <Fact label="Tenure" value={`${answers.tenureMonths} months`} />
          </div>

          {/* one-line why, for each */}
          <div className="space-y-3 mb-7 border-t border-rule pt-5">
            <WhyLine label="Why this amount">{affordability.reason}</WhyLine>
            <WhyLine label="Why this rate">{rateband.reason}</WhyLine>
            <WhyLine label="Why this EMI">{emi.reason}</WhyLine>
          </div>

          {/* the script */}
          <div className="bg-accentSoft border-l-2 border-accent px-5 py-4 print:bg-transparent print:border-l-2 print:border-ink">
            <p className="text-[.7rem] uppercase tracking-[.08em] text-muted font-body mb-1.5">
              If they quote higher
            </p>
            <p className="font-body text-[.95rem] text-ink italic">
              "Based on my income and profile, a fair rate here is {rateband.rateMin}%–{rateband.rateMax}%.
              Can you explain what's pushing your quote above that?"
            </p>
          </div>

          <p className="text-[.72rem] text-muted font-body mt-6 pt-4 border-t border-rule">
            Generated by Borrower Copilot from your own answers — not a bureau report or a lender offer.
            Confidence: {affordability.confidence >= 0.8 ? "High" : affordability.confidence >= 0.55 ? "Medium" : "Low, based on limited detail provided"}.
          </p>
        </div>
      </div>
    </div>
  );
}

function Fact({ label, value, strong }) {
  return (
    <div>
      <p className="text-[.7rem] uppercase tracking-[.08em] text-muted font-body mb-1">{label}</p>
      <p className={`font-mono ${strong ? "text-xl text-accent" : "text-lg text-ink"}`}>{value}</p>
    </div>
  );
}

function WhyLine({ label, children }) {
  return (
    <div>
      <p className="text-[.72rem] font-semibold text-ink font-body">{label}</p>
      <p className="text-[.85rem] text-muted font-body leading-snug">{children}</p>
    </div>
  );
}